# CodeRabbit Configuration
# Docs: https://docs.coderabbit.ai/guides/configure-coderabbit

language: en-US

reviews:
  # Enable auto-review on PRs
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main

  # Paths to ignore
  path_filters:
    - "!**/*.lock"
    - "!**/pnpm-lock.yaml"
    - "!**/package-lock.json"
    - "!**/.next/**"
    - "!**/node_modules/**"
    - "!**/dist/**"
    - "!**/*.min.js"

  # Review profile - assertive for thorough feedback
  profile: assertive

  # Request changes on high severity issues
  request_changes_workflow: true

  # Validate PRs against linked issues
  assess_linked_issues: true

  # High-level summary
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"

  # Review status in PR
  review_status: true

  # Poem in review (fun touch)
  poem: false

  # Collapse walkthrough after certain length
  collapse_walkthrough: true

  # Path-based instructions
  path_instructions:
    - path: "src/components/**/*"
      instructions: |
        Review React components for:
        - Proper TypeScript types (no `any`, prefer explicit types)
        - Accessibility (a11y) best practices (ARIA labels, keyboard nav)
        - Component composition patterns (prefer composition over inheritance)
        - Avoid inline styles, use Tailwind classes
        - Ensure components are properly memoized when needed

    - path: "src/app/**/*"
      instructions: |
        Review Next.js App Router code for:
        - Proper use of Server vs Client Components ('use client' directive)
        - Correct metadata exports for SEO
        - Server Actions security (validate all inputs, use zod)
        - Proper error boundaries and loading states
        - Correct use of route handlers and middleware

    - path: "**/*.test.{ts,tsx}"
      instructions: |
        Review unit tests for:
        - Meaningful test descriptions (describe what, not how)
        - Proper use of testing-library queries (prefer getByRole, getByLabelText)
        - No implementation details in tests (test behavior, not internals)
        - Proper setup/teardown patterns
        - Good coverage of edge cases

    - path: "src/lib/**/*"
      instructions: |
        Review utility functions for:
        - Pure functions where possible (no side effects)
        - Proper error handling (throw typed errors, use Result pattern)
        - TypeScript generics used appropriately
        - Functions should be small and focused (max-lines-per-function: 30)
        - Comprehensive JSDoc comments for public APIs

    - path: "src/actions/**/*"
      instructions: |
        Review Server Actions for:
        - Input validation with zod schemas (CRITICAL for security)
        - Proper authentication checks before any data mutation
        - Authorization verification for resource access
        - Rate limiting considerations
        - Proper error responses (don't leak internal details)
        - Database transaction handling where needed

    - path: "e2e/**/*"
      instructions: |
        Review E2E tests for:
        - Proper use of Playwright locators (prefer getByRole, getByTestId)
        - Avoid flaky selectors (no xpath, avoid nth-child)
        - Proper wait strategies (waitForSelector, waitForResponse)
        - Test isolation (tests should not depend on each other)
        - Meaningful assertions that verify user-visible behavior

  # Tools configuration
  tools:
    # Built-in tools
    shellcheck:
      enabled: true
    markdownlint:
      enabled: true
    # Language-specific
    biome:
      enabled: false
    eslint:
      enabled: true
    # Security tools
    semgrep:
      enabled: true
    gitleaks:
      enabled: true

  # Pre-merge checks
  pre_merge_checks:
    title:
      mode: warning
      requirements: "Must follow conventional commits (feat:, fix:, docs:, chore:)"
    description:
      mode: warning
    docstrings:
      threshold: 80
      mode: warning
    custom_checks:
      - name: "Linear Issue Linked"
        instructions: "PR body must contain 'closes BAS-' or 'fixes BAS-' followed by a number, OR the branch name must contain 'BAS-' followed by a number. If neither is present, fail with a suggestion to link a Linear issue."
        mode: warning

  # Finishing touches - on-demand generation
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

# Knowledge base settings
knowledge_base:
  learnings:
    scope: auto
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/CLAUDE.md"
      - ".claude/docs/rules/coding-style.md"
      - ".claude/docs/rules/security.md"
      - ".claude/docs/rules/testing.md"
      - ".claude/docs/rules/patterns.md"

chat:
  # Enable chat interactions
  auto_reply: true
  # Issue tracking integration (Linear)
  # Enables: PR validation against linked issues, one-click issue creation
  # Setup: Install Linear GitHub integration at https://linear.app/settings/integrations/github
  integrations:
    linear:
      usage: auto
