# Codecov Configuration
# Docs: https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 1% # Allow 1% drop before failing (stricter)
        informational: false # Make it blocking
    patch:
      default:
        target: 80% # New code should be well tested
        informational: false # Make it blocking

  # Round coverage to 2 decimal places
  precision: 2

comment:
  # PR comment layout
  layout: "diff, flags, files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

# Flags for different test types
flags:
  unit:
    paths:
      - src/
    carryforward: true

# Ignore paths that shouldn't be tracked
ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/node_modules/**"
  - "**/.next/**"
  - "**/coverage/**"
  - "e2e/**"
  - "scripts/**"

# GitHub integration
github_checks:
  annotations: true
